services:
  - type: web
    name: backend-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        value: your-mongodb-connection-string
      - key: JWT_SECRET
        value: your-secret-key
    autoDeploy: true
    branch: main
    region: oregon
    repo: https://github.com/your-username/your-backend-repo
